# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-glue-workflow
  description: This component provisions Glue workflows
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component







